apiVersion: v1
kind: Service
metadata:
  name: labflow
  labels:
    app: labflow
spec:
  type: ClusterIP
  selector:
    app: labflow
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
